version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  agent: datadog/agent@0.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - agent/setup
workflows:
  example-workflow:
    jobs:
      - example-job